Date:		 1-OCT-1985 16:06:45
From:		SQPHIL@UK.AC.LIVERPOOL.CSVAX
To:		syskermit@UK.AC.LANCS.VAX1


Dear Alan,
          I heard through Martin Beer that Sak Wathanasin had
produced a settings file for Mac Kermit to configure it for an
English Keyboard. I have also done this, but I have given it
some extra features.. Namely

1) ESC key
2) Arrow keys  (Command I,J,K and M)
3) Numeric Keypad keys in Numeric Keypad Application Mode, so that EDT et al
   may be used with the Macintosh.

 I've also produced some documentation for it in MacWrite 1.0 format,and I'm
awaiting a copy of the latest version of Macwrite so that instead of there
being 5 documentation files there can be one large one (its full of pictures
of MacKermit in action). I can supply that as well in Hqx format.
As you know, we will supply MacKermit on 3.5" disk, plus my settings file
and documentation to anyone who wants it! If you're interested let me know.

Phil Jimmieson
Computer Science Dept
University of Liverpool

[Files are CKMKB2.HQX for settings file and CKMKB2.DOC for the concatenated
 documentation files - Alan]
