From:	Sak Wathanasin   <sakw@svga> 19-SEP-1985 21:09
To:	SYSKERMIT
Subj:	Configuring MacKermit for UK keyboard
From:       Sak Wathanasin   <sakw@svga>


File CKMKBD.HQX is a hexed version of the "settings" file for use with
C-KERMIT on a Macintosh with UK keyboard. Simply download to the Mac and
unhex with BinHex 4.0

Sak Wathanasin, U of Sussex, Cognitive Studies, Falmer, Sussex BN1 9QN, UK
uucp:...mcvax!ukc!cvaxa!sakw  arpa/janet: sakw%svga@uk.ac.ucl.cs
