Date: 21-APR-1986 16:19:17
From: SYSKERMIT%vax1.central.lancaster.ac.uk@cs.ucl.ac.uk
To: "SY.FDC" <@cs.ucl.ac.uk,@cs.ucl.ac.uk,@MIT-MULTICS.ARPA:SY.FDC@cu20b.ARPA>
Subject: Mac Kermit 0.8(034) keyboard settings files for UK keyboards

Hi Frank - Here's two settings files for C-Kermit 0.8(034) on Mac and
Mac Plus with UK keyboards, from Phil Jimmieson of Liverpool University.
(SQPHIL @ UK.AC.LIV.CSVAX)

                  Alan

--------------cut here for the Mac plus-------------------------
(This file must be converted with BinHex 4.0)

:#deTFh-J8'PRChNV!&4&@&4,49*0!*!)"Ibi[`#3"!%!N!-&3J!!"%)!N!1k!*!
(m'!!N!3-!*!&8!$)m'C993#3!``!!!Y0DA0c)&"TCfGj+`)!N!0849K85d9563%
!N!P849K85d9563%!N!GG6`#3#'8r!*!%QU,hD3#3"JAm3Q&N)'0SBA*KBh4PFL"
TEL"ZB@eP,#"[FL"MB@iRG#"QD@jN)(4SBA3JC'PcDbi!N!4+!!%!N!8d!(!!4J#
k"!*25`#3"3i!$!!Z!,b)+N%JFhPcG'9Y)'9bFQpb)'pMBh9bFQ9N1b"`E'9KFf8
JG(*j)'&RB@PZ,J#3!dS!N!-i!!!PJ!#3!f8!N!F&!*!,"`#3!`S!N!0D!*!$@J#
3!eJ!N!F#!*!$+J#3!aJ!!!d0!3%!32q0rl8!i`'e!*!&Z!%`!*!$!J%E!*!$c'J
$'dp`!aYE33-E@d3$'eY$!aYE3J-E6h8$'dpf!aY2G`-E6hJ$'dpj!aY2E3-E6e!
$'dp4!aY28J-E-&-$'c"Y!aX`E!-E-%d$'c"Z!!-E-(!$'c"a!aX`FJ-E-(-$'c"
d!aX`G3-E-(B$'c"h!aX`H!-E-(N!N%B$'eY"!aYE3J-E@d3$'eY$!!!$%!!!#3#
3!`J!N!-%!'&cC'CSChTiBhB!BR&hCA*jG$%b-c3f06dj0bdi-&e[G9YTF!eXDLG
V1e`X,fjY,JNJ'hrq!*!-NS-!N!1#Li3!N!14JBm!N!18PCDAQ*QDQ`#FR3#3)N&
64%C)4eTB3eB!3P&A49*C9#&!)b4H*5XS*PmU+Ae29AY*8!e-5L*,1R`m2dj02JN
JIJMr!*!-,Si!N!13!)Z-!*!$rSdY!*!$-$%b-c3e0MF!1$N!N#*"8d4'5%GD@%0
@!%*49d95@93a-M-d0M8p16FY1$"G6e9E59!06%SR5cYF,#p165i*)'!)$3#3$)b
$!*!$JSZ%!*!$MB'+!*!$J)'#Ji5&KSF!L)N!N#*"8d4'5%GD@%0@!%*49d95@93
K3#-NAL8V+#CI+LPp6e9l59!06%SL5cTm2$p166i*)(i)$3#3$#k1!*!$JSZ-!*!
$rSdY!*!$-$%b-c3e0MF!1$N!N#)"%`3'#!FD'!-@!!)4&`85'43a-M-d0M8p16F
Y1$"G$a9E#4!0$!SR#cXF,#m1$5i*)2m)$3#3$#iU!*!$+`!X!*!$#LmY!*!$-$%
b-c3e0MF!1$N!N#)"%`3'#!FD'!-@!!)4&`85'43K!#-N(L8V+#BI+LNG$a8E#4!
0$!SF#cSF2$m1$6i*)"i)$3#3$#iU!*!$+`!X!*!$#LmY!*!$-$%b-c3e0MF!1$N
!N#6,h!!!bq!!N!3"!*!$"8)!!!4#!*!$ZJ!!c#3"HJ#3!a`!JJ!%8d&@53#3!bT
639C$!*!$0Ne6493!N!0#4P0&9!#3!dj,8d98!*!$@J!$rrm!N!N$rrm!N!-m!*!
&!J#3"9J!!-[J!!)!&`#3!ei!!-[F!!)!,!!!!5i!!-[S&NYPFQeTG#"YCA4K)'Y
PH5"`FQ9QDAJ85f9bE@Pd)'CeEQ0dD@pZ)'YPHA-,5f9bE@Pd)%YPHA2G@J:

---------------down to here for the Macplus----------------------


--------------cut here for the Mac-------------------------------
(This file must be converted with BinHex 4.0)

:#NeTFh-J8'PRChN!9%9B9%Y&8Nd!N!J&qdr*!*!%!3#3!`9"!!!%33#3!lS!N#!
+6@PcFb"3D@GRH@F#!*!$9%9B9%Y&8Nd"!*!*9%9B9%Y&8Nd"!*!6!GJ!!*QBVrN
!N!B&q`#3K6J!!#@!!*!$C3#3"`8!N!X(!*!$#J#3!eS!N!0D!*!$@!#3"`)!N!-
U!*!$'!!!$3d"!3#3!`%!N!NK!*!$(J#3!`)"'`#3!mYS!aY2F!-E@d%$'eY%!aY
E3`-E@d)$'dpe!aY2GJ-E6hF$'dpi!aY2H3)E6`-E6e!$'dp4!aY28J-E6e-$'dp
Y!aY2E!-E6dd$'dpZ!!-E6h!$'dpa!aY2FJ-E6h-$'dpd!aY2G3-E6hB$'dph!aY
2H!-E6hN!N%B$'eY"!aYE3J-E@d3$'eY$!!!$%!!!#3#3!`J!N!-%!'&cC'CSCea
kH'-[GR&hCA*jG$%b-c3f06dj0bdi-&e[G9YTF'"XDLGV1`eY,Q*Z,!Rq'hmJ!*!
-,LS!N!-VK#`!N!-+,bd!N!-`-6)c0$8f0`!i13#3)N&64%C)4haD@%-r9P&A49*
C9#&!)b4H*5XS*PmU+Ae29AY*8(j-5L*,1Je02N*12!Rq)hmJ!*!-,LS!N!-V!#`
!N!-+,bd!N!-`-6)c0$8f0`!i13#3)N&64%C)4eaD@%-[9P&A49*C9$%b-c3f06d
j0bdi-&e299Y*8'"-5LG,1`e0,N*1,!Rq'hmJ!*!-M)m!N!11!*%!N!10N!#+!*!
$J)'#Ji5&KSF!L)N!N#*"8d4'5%Gm@PK$2eC49d95@93K3#-NAL8V+#CI+LPp6e9
l59"q6%SL5cS066j#6M`*rL0r)!#3$#iU!*!$+`!X!*!$#LmY!*!$-$%b-c3e0MF
!1$N!N#)"%`3'#!GF'KJ$,aB4&`85'45,M)f1N!#226Q4,C)`A3m9@i%3B!b#*i-
l$B3Z!JiX#IiEIb!!N!`Z+J#3!bX!,!#3!`S[,3#3!c!a-M-d06Bh!$Jj!*!L!4-
%"JJ('KSB!cm@%4F&%KN8PCDAQ*UC+jfE(jb8(3m9'i%3IJb#)S-k$B3q!Jim#Ii
EIb!!N!`Z+J#3!bX!,!#3!`S[,3#3!c!a-M-d06Bh!$Jj!*!Nbm`!!-[3!*!%!3#
3!`9"!!!%33#3!lS!!-`B!$i!N!-F!))!"&0"9NN!N!-U8d&@3`#3!cC08d98!*!
$3NC6493!N!015e0&9!#3!eS!!rrr!*!*!rrr!*!$2!#3"3)!N!9B!!$,d!!#!"F
!N!0H!!$,c!!#!#`!!!%Y!!$,f"C,CA*YDA3JE@9dB5"VCANJF(*PCQPi&%YPFQe
TG#"QG@jMG'P[EL"VCAPc#dYPFQeTG#",CAPcFq3:

---------------down to here for the Mac-------------------------


